### ISSUE TITLE
mongodb 3.6 ? 1.6.1 ?

### ISSUE THREAD

**Issue by crapthings** [meteor/meteor-feature-requests#233] opened 2017-12-07 01:43 UTC
https://docs.mongodb.com/manual/release-notes/3.6/#known-issues-in-3-6-0

**Comment by StorytellerCZ** [comment] 2017-12-07 08:35
What is this about?
MongoDB 3.6 discussion is already happening:
https://github.com/meteor/meteor-feature-requests/issues/152
https://github.com/meteor/meteor-feature-requests/issues/158

**Comment by jamesgibson14** [comment] 2017-12-08 16:11
A pretty simple request to add MongoDB 3.6 and the latest node driver to Meteor, after that we can continue to have discussions on how best take advantage and implement the new features like change notifications, expressive queries in Minimongo, etc.

**Comment by hwillson** [comment] 2017-12-12 13:11
Taking change streams out of the picture for now, we can still move ahead with updating the Meteor Tool to use Mongo 3.6. Marking as `pull-requests-encouraged` if anyone is interested in helping out!

**Comment by hwillson** [comment] 2018-02-26 13:55
Quick FYI - this work is being handled in https://github.com/meteor/meteor/pull/9632.

**Comment by klaussner** [comment] 2018-07-07 17:46
MongoDB has been updated to version 3.6 in Meteor 1.7.

**Closed by klaussner** 2018-07-07 17:46 UTC
Labels: Project:Mongo Driver, confirmed, pull-requests-encouraged

**Comment by rijk** [comment] 2018-07-12 12:59
The error reported in https://github.com/meteor/meteor/issues/9753 is still happening when using the `aggregate()` function with Meteor 1.7.0.3.. Are you guys aware of this?

**Comment by klaussner** [comment] 2018-07-12 13:17
@rijk Can you open a new issue for that (with a reproduction repo)? :slightly_smiling_face:

**Comment by rijk** [comment] 2018-07-12 14:18
@klaussner while creating the reproduction repo, I found out that this is not strictly a bug, but a subtle change of API between Meteor 1.6/Mongo 3.4 and 1.7/3.6. Namely, the `.aggregate()` function used to directly return an array, but now it returns an `AggregationCursor`. I have to manually call `toArray()` after `aggregate()`. Not sure if this was an intended change, though.

**Comment by klaussner** [comment] 2018-07-12 15:07
Yes, that's an intended change. The new version of the MongoDB driver used in Meteor 1.7 is a major update with a few breaking changes that you need to consider if you a using the "raw" driver functions. See also https://github.com/meteor/meteor/issues/9936#issuecomment-394514613.
