### ISSUE TITLE
Parallelization during builds

### ISSUE THREAD

**Issue by aas395** [meteor/meteor-feature-requests#396] opened 2020-04-19 00:40 UTC
My app takes about 5 minutes to build on my local machine. It takes 10 minutes in AWS CodeBuild using the 4-core instance option, and the difference mostly seems to be in processor-intensive tasks, like compiling our typescript files. I thought if I upgraded to the next tier up, which uses an instance with 8 cores, that my build time would be reduced, but it ended up being the same. Due to the way CodeBuild is set up, there's no way to make our builds go faster by adding cores. It would be great if we could use the additional cores to speed up build times.

**Comment by nathanschwarz** [comment] 2021-01-19 16:26
duplicate of https://github.com/meteor/meteor-feature-requests/issues/334

**Comment by StorytellerCZ** [comment] 2021-04-24 09:02
Closing for duplication, please continue discussion in #334

**Closed by StorytellerCZ** 2021-04-24 09:02 UTC
Labels: Project:Build Farm
